# Generated by Django 4.0.5 on 2024-04-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_text', models.TextField()),
                ('date_posted', models.DateField()),
                ('time_posted', models.TimeField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
            ],
        ),
    ]
